# Generated by Django 2.2.4 on 2021-01-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20210119_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_of_appointment', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('rating', models.CharField(blank=True, max_length=128)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Client')),
                ('troupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Troupe')),
            ],
        ),
        migrations.CreateModel(
            name='ClownsViewClientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Appointment')),
                ('clown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Clown')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Appointment')),
                ('clown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Clown')),
            ],
        ),
    ]
